apiVersion: v1
kind: Service
metadata:
  name: triton-metrics
spec:
  type: NodePort
  selector:
    app: triton
  ports:
    - name: metrics
      port: 8002
      targetPort: 8002
      nodePort: 31002
